code --install-extension adpyke.vscode-sql-formatter
code --install-extension adrianwilczynski.alpine-js-intellisense
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bradlc.vscode-tailwindcss
code --install-extension codium.codium
code --install-extension dbaeumer.vscode-eslint
code --install-extension devsense.composer-php-vscode
code --install-extension devsense.intelli-php-vscode
code --install-extension devsense.phptools-vscode
code --install-extension devsense.profiler-php-vscode
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension jebbs.plantuml
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension naumovs.color-highlight
code --install-extension prisma.prisma
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension rocketseat.theme-omni
code --install-extension styled-components.vscode-styled-components
code --install-extension tobermory.es6-string-html
code --install-extension usernamehw.errorlens
code --install-extension wix.vscode-import-cost
code --install-extension xdebug.php-debug
code --install-extension zenclabs.previewjs
